name: test

on:
  discussion:
  discussion_comment:

env:
  T: "tTdly-Old"
  F: "ttdly"

jobs:
  testt:
    runs-on: ubuntu-latest
    steps:
      - uses: tTdly-Old/hello-world-javascript-action@main
      - run: printenv