name: test

on:
  discussion:
    types:
      - "created"
      - "edited"
  discussion_comment:

env:
  T: "tTdly-Old"
  F: "ttdly"

jobs:
  testt:
    runs-on: ubuntu-latest
    steps:
      - uses: tTdly-Old/hello-world-javascript-action@main
        with:
          who-to-greet: 'Mona the Octocat'