# name: Fliter bad issue and trans issue info to md file
name: issue2md

on:
  issues:
    types:
      - "opened"
env:
  ONWER: "tTdly-Old"
  REPO: "ttdly-old.github.io"
  EMAIL: tutoudenglongyu@163.com

permissions:
  pull-requests: write
  issues: write
  repository-projects: write  

jobs:
  issue2md:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.actor != env.ONWER}}
        name: Checkout Main
        uses: actions/checkout@v3.3.0
        with: 
          ref: main
      - if: ${{ github.actor != env.ONWER}}
        name: Comment Close and Lock Issue
        run: bash ./.github/script/issue-filter.sh ${{env.ONWER}} ${{env.REPO}} ${{github.event.issue.number}} ${{secrets.TOKEN}}
      - if: ${{ github.actor == env.ONWER}}
        name: Checkout issue2md
        uses: actions/checkout@v3.3.0
        with:
          ref: issue2md
          fetch-depth: 0
      - name: Run Issue to Md Script
        run: bash ./.github/script/issue2md.sh ${{env.ONWER}} ${{env.REPO}} ${{github.event.issue.number}} ${{secrets.TOKEN}}
      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "pages(create): pages/${{github.event.issue.number}}.md  ${{github.event.issue.title}}  ${{github.event.issue.created_at}}BY github actions"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with: 
          branch: issue2md
          github_token: ${{secrets.GITHUB_TOKEN}}
# - name: Set Git Info
#   run: |
#     git config user.name ${{env.ONWER}}
#     git config user.email ${{env.EMAIL}}
# - name: Commit and push
#   run: |
#     git add . && git commit -m 'pages(create): pages/${{github.event.issue.number}}.md  ${{github.event.issue.title}}  ${{github.event.issue.created_at}}BY github actions'
#     git push  https://${{env.ONWER}}:${{secrets.TOKEN}}@github.com/${{env.ONWER}}/${{env.REPO}}.git issue2md

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#       with:
#         ref: ${{ github.head_ref }}
#         fetch-depth: 0
#     - name: Commit files
#       run: |
#         git config --local user.email "github-actions[bot]@users.noreply.github.com"
#         git config --local user.name "github-actions[bot]"
#         git commit -a -m "Add changes"
#     - name: Push changes
#       uses: ad-m/github-push-action@master
#       with:
#         force_with_lease: true