# name: Fliter bad issue and trans issue info to md file
name: issue2md

on:
  issues:
    types:
      - "opened"
env:
  ONWER: "tTdly-Old"
  REPO: "ttdly-old.github.io"
  EMAIL: tutoudenglongyu@163.com

permissions:
  pull-requests: write
  issues: write
  repository-projects: write  

jobs:
  issue2md:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.actor != env.ONWER}}
        name: Checkout Main
        uses: actions/checkout@v3.3.0
        with: 
          ref: main
      - if: ${{ github.actor != env.ONWER}}
        name: Comment Close and Lock Issue
        run: bash ./.github/script/issue-filter.sh ${{env.ONWER}} ${{env.REPO}} ${{github.event.issue.number}} ${{secrets.TOKEN}}
      - if: ${{ github.actor == env.ONWER}}
        name: Checkout issue2md
        uses: actions/checkout@v3.3.0
        with:
          ref: issue2md
      - name: Run Issue to Md Script
        run: bash ./.github/script/issue2md.sh ${{env.ONWER}} ${{env.REPO}} ${{github.event.issue.number}} ${{secrets.TOKEN}}
      - name: Set Git Info
        run: |
          git config user.name ${{env.ONWER}}
          git config user.email ${{env.EMAIL}}
      - name: Commit and push
        run: |
          git add . && git commit -m 'pages(create): pages/${{github.event.issue.number}}.md  ${{github.event.issue.title}}  ${{github.event.issue.created_at}}BY github actions'
          git push  https://${{env.ONWER}}:${{secrets.TOKEN}}@github.com/${{env.ONWER}}/${{env.REPO}}.git issue2md


