name: issue2md

on:
  issues:
    types:
      - "opened"
env:
  ONWER: "tTdly-Old"
  REPO: "ttdly-old.github.io"
  EMAIL: tutoudenglongyu@163.com

permissions: write-all

jobs:
  issue2md:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.actor != env.ONWER}}
        name: Comment Close and Lock Issues
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{secrets.TOKEN}}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{env.ONWER}}/${{env.REPO}}/issues/${{github.event.issue.number}}/comments \
            -d '{"body":"Sorry, I don'\''t accept other people'\''s issues now. So the issue was automatically closed and locked. Thanks and good luck."}'
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{secrets.TOKEN}}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{env.ONWER}}/${{env.REPO}}/issues/${{github.event.issue.number}} \
            -d '{"state":"close","state_reason":"not_planned"}'
          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{secrets.TOKEN}}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{env.ONWER}}/${{env.REPO}}/issues/${{github.event.issue.number}}/lock \
            -d '{"lock_reason":"off-topic"}'

      - if: ${{ github.actor == env.ONWER}}
        name: Checkout issue2md
        uses: actions/checkout@v3.3.0
        with:
          ref: issue2md
          fetch-depth: 0

      - if: ${{ github.actor == env.ONWER}}
        name: Run Issue to Md Script
        run: bash ./.github/script/issue2md.sh ${{env.ONWER}} ${{env.REPO}} ${{github.event.issue.number}} ${{secrets.TOKEN}}

      - if: ${{ github.actor == env.ONWER}}
        name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "pages(create): pages/posts/${{github.event.issue.number}}.md"

      - if: ${{ github.actor == env.ONWER}}
        name: Push changes
        uses: ad-m/github-push-action@master
        with: 
          branch: issue2md
          github_token: ${{secrets.GITHUB_TOKEN}}
