name: md2page

on:
  push:
    branches:
      - "issue2md"

permissions: write-all

jobs:
  md2page:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout issue2md
      uses: actions/checkout@v3.3.0
      with:
        ref: issue2md
        fetch-depth: 0

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      id: pnpm-install
      with:
        version: 7.27.0
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: pnpm run build
    
    - name: Show directory
      run: |
        ls -A

    - name: Checkout gh-pages
      uses: actions/checkout@v3.3.0
      with:
        ref: gh-pages
        fetch-depth: 0

    - name: Copy files
      run: |
        ls -A
        rm -rf ./dist/assets
        mv -f ./dist/* ./

    - name: Commit changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "build pages ${{ github.run_id }}"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with: 
        branch: gh-pages
        github_token: ${{secrets.TOKEN}}

