name: test
on:
  workflow_call:
      inputs:
        build_id:
          required: true
          type: number
        deploy_target:
          required: true
          type: string
        perform_deploy:
          required: true
          type: boolean



jobs:
  testt:
    runs-on: ubuntu-latest
    steps:
      - run: printenv