name: test
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'



jobs:
  testt:
    runs-on: ubuntu-latest
    steps:
      - run: printenv