name: test

on: push

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: if not exit dir then create
        run: |
         echo -e  "if [[ ! -d \"~/.ssh\" ]]; then \n mkdir ~./ssh \n fi;" > mkifnex.sh
         bash mkifnex.sh
         echo "okok" > ~/.ssh/id_rsa.pub
         cat ~/.ssh/id_rsa.pub

