name: test

on: pull_request
env: 
  EMAIL: 123@ee.com
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: chekout main
        uses: actions/checkout@v3.3.0
        with:
          ref: main
      - run: |
        git config user.name "${{github.actor}}"
        git config user.email "${{env.EMAIL}}"
        git config --list