name: test

on: push

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          ls
          ls ~/.ssh
          echo "okokok" > ~/.ssh/id_rsa_pub
          jq --help

