name: test

on:
  issues:
    types:
      - "opened"

env:
  T: "tTdly-Old"
  F: "ttdly"

jobs:
  testt:
    runs-on: ubuntu-latest
    if:  github.actor != vars.ONWER
    steps:
      - run: echo "ERROR"
  test2:
    runs-on: ubuntu-latest
    env: 
      BODY: ${{toJSON(github.event.issue.body)}}
    if:  github.actor == vars.ONWER
    steps:
      - run: echo "$BODY"
      - run: echo ${{ github.repository }}