name: test

on: push
env: 
  EMAIL: 123@ee.com
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: chekout main
        uses: actions/checkout@v3.3.0
        with:
          ref: main
      - run: |
          git config user.name "${{github.actor}}"
          git config user.email "${{env.EMAIL}}"
          git config --list
      - run: |
          bash ./.github/scripts/issue2md.sh ${{github.actor}} ${{env.EMAIL}} 3 ${{env.EMAIL}}
          ls -a
          cat ./pages/${{env.EMAIL}}.md
